Repository BrutalCoding/shady.ai, pull requests merged in 2023-04, with the labels that each got.

#2 Add improved git hooks and linter analysis
  .fvm/fvm_config.json
  .lefthook/commit-msg/conventional_commit
  CODEOWNERS
  lefthook.yaml
  shady_ai_flutter/analysis_options.yaml
  shady_ai_flutter/conventional_commit.sh
  shady_ai_flutter/lefthook.yaml
  shady_ai_flutter/lib/main.dart
  shady_ai_flutter/pubspec.yaml
  shady_ai_flutter/test/widget_test.dart
Labels: enhancement

#6 fix: Wrong working directory in web_app.yaml
  .github/workflows/web_app.yaml
Labels: bug

#20 Fix typos and some grammar in README
  README.md
Labels: documentation
